### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-embed-images#4]
Hey @dherges! I just did some updates that I hope you’ll like.
Could you add me as an npm collaborator, and potentially cut a 1.0.0 release?

**Comment by dherges** [comment]
What do i have to do? Can we run npm releases on an npm org account?

**Comment by wooorm** [comment]
Oh well I just set [an org](https://www.npmjs.com/org/remarkjs) up, never used it before though, so let’s see how it works. I added you, could you add the project to the org (I believe you must go to your profile settings, then the org, teams, developers packages, and then add it)!

**Comment by dherges** [comment]
```bash
$ npm owner add wooorm remark-embed-images
+ wooorm (remark-embed-images)
```

I was able to add you as owner of the package. But didn't find a way ot add it to the remarkjs org.

--edit

Circle CI is not being run anymore. I used to do [`yarn release`](https://github.com/remarkjs/remark-embed-images/blob/master/package.json#L43), then push the tag to github. Circle CI would run [`npm publish`](https://github.com/remarkjs/remark-embed-images/blob/master/.circleci/config.yml#L45) (with an npm token on the circle ci project)

**Comment by wooorm** [comment]
Hmm, weird. I guess admins must add packages then? 🤔 Thanks for checking!

About Circle: I used to do that too, release from CI on tags, but that’s vulnerable. Now I do it by hand (npm publish), and I have [2FA](https://docs.npmjs.com/getting-started/using-two-factor-authentication) turned on for extra security!

How can we turn Circle back on?

**Comment by dherges** [comment]
Think you need to go login with your github account at circleci.com, then switch to the github org, go to "Add Projects" and pick the remark-embed-images repo from the list. It should pick up the configuration file automatically.

**Comment by wooorm** [comment]
OK Circle is back again!
