### ISSUE TITLE
How to support images relative to a file?

### ISSUE THREAD

**Issue by Torbet** [remarkjs/remark-embed-images#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

When using remark-embed-images for inline images, I have to reference the image from the root of my project, for example:

in /notes/Articles/post.md, for an image in the same folder to render, I need to reference it as !(image)[notes/Articles/Image.png]

### Solution

as they are in the same folder, I would like to be able to add images relatively like: !()[./Image.png]

adding images relative to the current file would be huge, as referencing from the root in my markdown editor does not display images.

### Alternatives

full path, self hosting, all annoying

**Comment by wooorm** [comment]
You can start images with `./` or `../` and it’ll work: https://github.com/remarkjs/remark-embed-images/blob/main/test/index.js. Please make your problem reproducible

**Comment by Torbet** [comment]
Does that only work when reading the md file with to-vfile?

**Comment by Torbet** [comment]
Or a way to specify the path when given plaintext markdown content?

**Comment by Torbet** [comment]
> m

I managed to workaround my mimicking the vfile object and adding a cwd to the markdown content - seems to work okay!

**Comment by wooorm** [comment]
You can pass a vfile. You can also pass any argument that vfile supports (such as an object with a `path`).

Without such information, plugins that use the file system have no clue where things are!
